--- 
name: Create PR

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        options: 
        - test
        - test/1
        - test-1
        - test_1
        - 1234 
      content: 
        required: true
        default: 'test'

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: change contents 
        run: |
          echo '${{ github.event.inputs.content }}' >> content.txt
      - name: generate branch name
        run: |
          echo '::set-output name=branch::${{ github.event.inputs.branch }}'
      - uses: actions/github-script@v6
        with:
          script: |
            owner = "hairmare"
            repo = "oktoki-action-pr-test"
            commit = octokit.rest.repos.getCommit({
              owner,
              repo,
              ref,
            });
            console.log(commit)